# Generated by Django 3.0.2 on 2020-02-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgurl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
